apache/ozone-site

content/community.md, layouts/partials/header.html
Add **Community** menu.
This page contains Ozone mailing list, Ozone slack, Ozone community call.
But there is a question: Should I add past mailing archives to this page?
Like this http://mail-archives.apache.org/mod_mbox/hadoop-ozone-dev/
https://issues.apache.org/jira/browse/HDDS-4415
Locally with hugo.
=> HDDS-4415. Add mail lists page on ozone website

.asf.yaml
* Only allow squash merge.
* Send issue/PR updates to `issues@`, not `dev@`.
* Add PR link and label in Jira.
https://issues.apache.org/jira/browse/HDDS-5036
Not tested, but same settings worked for other Ozone repos.
=> HDDS-5036. Apply merge/notification settings to ozone-site repo

README.md, content/downloads.md, content/release/0.2.1-alpha.md, content/release/0.3.0-alpha.md, content/release/0.4.0-alpha.md, content/release/0.4.1-alpha.md, content/release/0.5.0-beta.md, content/release/1.0.0.md, layouts/custompage/downloads.html, layouts/partials/footer.html, layouts/release/single.html
JIRA: https://issues.apache.org/jira/browse/HDDS-5096
Apache Ozone is separated from Apache Hadoop, it's not a Hadoop subproject anymore but a top-level Apache project (TLP).
The release page should be updated to use the new release artifact name scheme. (Old releases can be marked with a Hadoop flag to use the old URL scheme for releases before 1.1.0)
(some trivial typos / copyright year is also updated in this patch and very old releases are removed from the download page).
To test, create a `content/release/1.1.0.md` file:
```
---
title: Release 1.1.0 available
date: 2021-03-02
linked: true
---
TODO
```
And start the preview:
```
hugo serve
```
And check the download page: http://localhost:1313/downloads/
=> HDDS-5096. Adjust download pages to use Apache Ozone (tlp) artifacts

layouts/index.html
Fixing Index.html to point to 1.1.0 release instead of 1.0.0 release.
=> HDDS-5121. Fixing index.html to point to 1.1.0 release.

downloads/index.html
This reverts commit 147e2c74accef371bb25c407e34849d72407016d.
The change is reverted since it needs to be updated in the master branch first.
=> Revert "HDDS-5070. Fix broken download links for 1.1.0. (#9)"

content/release/1.1.0.md, layouts/custompage/downloads.html
Ozone tar files uploaded to the old hadoop namespace. As Ozone is not Hadoop any more they supposed to be uploaded to  the ozone project space. 
I moved the artifacts:
```
svn mv https://dist.apache.org/repos/dist/release/hadoop/ozone/ozone-1.1.0 https://dist.apache.org/repos/dist/release/ozone/1.1.0
```
But proper linking requires this one flag turning off.
=> HDDS-5121. fix download page to use ozone space instead of hadoop

content/downloads.md, layouts/custompage/downloads.html, layouts/release/single.html
* Fix verify commands to have `--`, not some HTML entity.
* Fix checksum/signature URLs.
https://issues.apache.org/jira/browse/HDDS-5694
```
hugo serve
open http://localhost:1313/downloads
open http://localhost:1313/release/1.1.0/
```
Verified dashes in commands.
Verified checksum/signature URLs work and refer to downloads.apache.org, not dist.apache.org.
=> HDDS-5694. Download page must not use dist.apache.org

layouts/release/single.html
Replace leftover link to hadoop.apache.org with ozone.apache.org.
https://issues.apache.org/jira/browse/HDDS-6006
```
hugo serve
open http://localhost:1313/release/1.1.0/
```
=> HDDS-6006. Leftover links pointing to hadoop.apache.org

config.toml, layouts/partials/header.html
> A menu is a named array of menu entries accessible by name via the `.Site.Menus` site variable. For example, you can access your site’s `main` menu via `.Site.Menus.main`.
Ozone website defines `menu.main` in `config.toml`, but does not access it, nor do the menu items appear in the generated `asf-site` branch.  Thus I think we can remove this menu definition leftover from Hadoop.
Also rename `div id` leftover from Ratis.
https://issues.apache.org/jira/browse/HDDS-6008
```
hugo serve
open http://localhost:1313
```
=> HDDS-6008. Remove leftover main menu definition

.gitignore, content/release/1.2.1.md, layouts/index.html
Replace references to 1.2.0 on the website with 1.2.1. https://ozone.apache.org/release/1.2.0/ should now redirect to https://ozone.apache.org/release/1.2.1.
If we want to leave 1.2.0 on the website and simply add 1.2.1 like a normal release, I can modify the PR to do this instead.
Page content and redirect tested locally with `hugo serve`.
=> HDDS-6136. Update Ozone site release page for 1.2.1

content/release/0.5.0-beta.md
https://issues.apache.org/jira/browse/HDDS-7359
Tested locally with `hugo serve`. Verified that 0.5.0-beta row is gone from download page with this change.
=> HDDS-7359. Remove Ozone 0.5.0-beta download link from the website

layouts/partials/header.html, static/style.css
Add Ozone logo to the website.
https://issues.apache.org/jira/browse/HDDS-4903
Chrome:
Firefox:
Safari:
=> HDDS-4903. Add Ozone logo to the website

content/release/0.2.1-alpha.md, content/release/0.3.0-alpha.md, content/release/0.4.0-alpha.md, content/release/0.4.1-alpha.md, content/release/0.5.0-beta.md, layouts/release/single.html
Added the "supported" flag and filtering in single.html based on this flag for docs.
=> HDDS-8516. Remove link to documentation for old releases

layouts/custompage/docs.html
Update the "edge" link on the Ozone website docs page to point to the content published on the website itself, instead of the one on Jenkins CI server.
https://issues.apache.org/jira/browse/HDDS-7678
`open https://ozone.apache.org/docs/edge/`
=> HDDS-7678. Link to the nightly doc on the Ozone website

.asf.yaml
Update .asf.yaml according to ASF [docs](https://s.apache.org/asfyaml) to support auto-linking Jira issues when they are typed in a comment in this repo. For example, after this change HDDS-1234 would automatically be converted into a Jira link.
According to https://gitbox.apache.org/schemes.cgi?ozone-site, the change will only take affect on the master branch, so I am not sure how to test it before merging.
=> HDDS-9604. Support jira auto linking between github and ozone-site repo.

.dockerignore, Dockerfile, README.md, compose.yml, package.json
This PR adds the required changes for creation of a docker file, which anybody can run with docker-compose and check changes on the go.
No package installations required.
- It will build an image with the node_modules already installed in it.
- `docker-compose up` will create a container with the local changes mounted on this container.
- Site will be available to view on `localhost:3000` (default port mapping in the container)
- While the site can be deployed without an image needing to be built, as discussed in the [JIRA](https://issues.apache.org/jira/browse/HDDS-9563), we can make the developer work much smoother with a containerized environment
- Any new contributor can just simply spin up a container from the image, and make changes in their local development directory
- These …
=> HDDS-9563. Containerize website development server

docusaurus.config.js, static/script/matomo.js
Add Matomo analytics to the new Docusaurus site. References are here:
[Matomo integration for the original Ozone website with Hugo](https://github.com/apache/ozone-site/pull/31/files)
[Example of integrating Matomo with a Docusaurus site from Apache Superset](https://github.com/apache/superset/pull/20398/files)
[Matomo Javascript client documentation](https://developer.matomo.org/guides/tracking-javascript-guide)
[ASF Matomo documentation](https://privacy.apache.org/matomo/)
I don't think we can test it until the new website is published.
=> HDDS-9573. Restore Matomo web analytics from the original website.

.github/workflows/publish.yml, README.md
Part 2/2. Requires #55 
Add github actions workflow to automatically build changes to the website v2 branch and commit the build artifacts to a staging branch. From here they can be published to a staging domain by the changes in #55.
Github actions workflow to build and commit the website was tested on my fork. It successfully built the site and committed to the specified branch. See [this commit](https://github.com/errose28/ozone-site/actions/runs/7218001805/job/19666723869) which pushed [these changes](https://github.com/errose28/ozone-site/commit/20d1f31fac0ede410e310c9c0348ccb7844554e9) to my test branch
=> HDDS-9926. Publish WIP website to staging branch (2/2)

.github/workflows/regenerate.yml
Upgrade GitHub actions to `v4` to get Node.js 20.
https://issues.apache.org/jira/browse/HDDS-10199
=> HDDS-10199. Node.js 16 actions are deprecated

.github/workflows/publish.yml
Update the checkout action to v4 since this supports node 20. Similar to #59 but for the new website feature branch.
HDDS-10203
Verified a test build of the site [succeeds on my fork](https://github.com/errose28/ozone-site/actions/runs/7645982361/job/20833793107).
=> HDDS-10203. Update Github actions to v4 since Node.js 16 actions are deprecated.

.github/scripts/pr_title_check.sh, .github/workflows/pull-request.yml
Copy the PR title check script and Github Action from the main Ozone repo to the new website.
I've left this in a separate file from the PR labeler in #68 since we might want to cherry pick this commit back to the main website development branch. Alternatively we could put both checks into the pull-request workflow.
HDDS-9603
- A [test PR](https://github.com/errose28/ozone-site/pull/2) on my fork failed the title check.
- I did not copy the bats tests since we would have to add a CI workflow for that here as well and manage the dependency which seems like overkill for a simple script that is already verified to work, but I'm open to suggestions here.
=> HDDS-9603. Add PR title check for ozone-site repo.

.github/labeler.yml, .github/workflows/label-pr.yml
Use https://github.com/actions/labeler to automatically label pull requests targeting the `HDDS-9225-website-v2` branch with the `website-v2` label. I kept forgetting to do it manually.
HDDS-10266
According to the [docs](https://github.com/actions/labeler?tab=readme-ov-file#initial-set-up-of-the-labeler-action) we can't test the change directly until merging it to the target branch (I added the `website-v2` label to the PR manually). However, I did set up a [mocked version in my fork](https://github.com/errose28/ozone-site/pull/1) that looks like it worked.
- The [labeler-test](https://github.com/errose28/ozone-site/tree/labeler-test) branch has the configuration committed
- A [PR](https://github.com/errose28/ozone-site/pull/1) against that branch had the `test-label` applied.
=> HDDS-10266. Auto label PRs for the new website.

.github/workflows/docusaurus.yml
Add smoketest that builds the website in CI.
https://issues.apache.org/jira/browse/HDDS-9568
Introduced broken link, verified the same steps fail with:
```
Error: Unable to build website for locale en.
...
[cause]: Error: Docusaurus found broken links!
...
- On source page path = /docs/system-internals/features/ratis-streaming:
-> linking to ./no-such-page (resolved as: /docs/system-internals/features/no-such-page)
...
```
CI:
https://github.com/adoroszlai/ozone-site/actions/runs/7740784527/job/21106463270
=> HDDS-9568. Add docusaurus build check in github actions

docusaurus.config.js, package.json, pnpm-lock.yaml
Docusaurus 3.1.1 was released earlier this month: https://docusaurus.io/blog/releases/3.1
It includes some bug fixes and a new feature to fail the build on broken markdown anchor (header) links.
1. Manually incremented docusaurus version in package.json since we are pinning it to an exact version. Commit the result.
2. Run `pnpm update '@docusaurus/*'` to install the latest version and regenerate the lockfile.
- This command automatically bumped `clsx` and `prism-react-renderer` as transitive dependencies since there was a minor version increase in docusaurus.
3. Commit the updated lockfile
[HDDS-10205](https://issues.apache.org/jira/browse/HDDS-10205)
Site remains functional in the following deployments:
Dev server: `pnpm run start`
Prod build: `pnpm run build && pnpm run serve`
Docker …
=> HDDS-10205. Upgrade Docusaurus to 3.1.1.

docusaurus.config.js, src/pages/index.js
After [HDDS-9564](https://issues.apache.org/jira/browse/HDDS-9564) was merged, the social media preview on the staging site was still broken. The image would not show up and the website's tagline was not displayed.
The social card was not displayed because the path to retrieve it is built from the `url` key in the docusaurus config, which was incorrectly set to `https://ozone.apache.org` instead of `https://ozone-site-v2.staged.apache.org` which did not match the staging domain the site is being hosted at.
The tagline was not displayed due to incorrect javascript formatting in the homepage.
See also HDDS-10313 to replace "redundant" with "reliable" which we can do after this is merged.
HDDS-100337
Modified the `url` config to http://localhost:300 and used [this browser …
=> HDDS-10337. Fix social media preview.

CONTRIBUTING.md
Most Ozone developers will not be familiar with javascript package management. To make it easy for them to update packages needed to build the website, add a high level explanation of pnpm files and commands for package management.
HDDS-10222
=> HDDS-10222. Add pnpm guide to contributing guide.

.github/scripts/curl.sh, .github/workflows/ci.yml, .github/workflows/docusaurus.yml, .github/workflows/publish.yml, CONTRIBUTING.md, compose.yml
Add a GitHub actions workflow to build the website from the docker image, then run and query the site with curl to check that it comes up.
This PR adds a ci.yml file as the main driver of the CI workflow, where each job is added as a separate workflow in its own file. When static analysis checks are introduced later, ci.yml will invoke them from static.yml before the build/run/publish checks.
Minor optimizations:
- The docker image only contains dependencies, and is cached.
- The website build is stored as an artifact and passed to the run and publish jobs
HDDS-10352
- An initial passing run on my [fork](https://github.com/errose28/ozone-site/actions/runs/7880065041)
- A [second passing run](https://github.com/errose28/ozone-site/actions/runs/7880109167) using the cached image to speed up …
=> HDDS-10352. Add GitHub Actions workflow to build and run the website.

.github/workflows/ci.yml, README.md
[HDDS-10352](https://issues.apache.org/jira/browse/HDDS-10352) moved the publish workflow to the main ci.yml file. As part of the move, the check incorrectly checked github.event instead of github.event_name in the trigger to run. This resulted in the publish workflow always being skipped.
HDDS-10400
- I pushed the same commit directly to the `HDDS-9225-website-v2` branch in my fork and the [publish workflow ran](https://github.com/errose28/ozone-site/actions/runs/7982396754).
- Publish workflow should not run on this PR's CI.
=> HDDS-10400. Fix website publish workflow.

.github/pull_request_template.md
Cherry pick of #70 to the GitHub default branch, which is now master. The PR template should actually be used after this is merged.
=> HDDS-10441. Add website PR template to default branch

.dockerignore, .github/workflows/static.yml, .gitignore, .licenserc.yaml, babel.config.js, docusaurus.config.js, progress.sh, sidebars.js, src/css/custom.css, src/css/footer.css, src/css/header.css, src/pages/index.js, src/theme/DocSidebar/index.js, src/theme/DocSidebar/index.module.css, static/doap_ozone.rdf, static/img/ozone-logo.svg
Use https://github.com/apache/skywalking-eyes to check license headers for website files. The main Ozone repo uses rat, but that requires Java and the website has no existing Java dependencies.
License headers have been added to files based on recommendations by the [skywalking eyes project](https://github.com/apache/skywalking-eyes?tab=readme-ov-file#github-actions) and [Apache policy](https://www.apache.org/legal/src-headers.html#faq-exceptions).
Although the skywalking-eyes project seems reasonably well maintained and [widely used by other apache projects](https://github.com/apache/skywalking-eyes/network/dependents?owner=apache&dependent_type=REPOSITORY&owner=apache), it is still using an [old version](https://github.com/apache/skywalking-eyes/blob/ed436a5593c63a25f394ea29da61b0ac3731a …
=> HDDS-9567. Add GitHub Actions license header check for relevant files.

.github/labeler.yml, .github/scripts/yamllint.sh, .github/workflows/label-pr.yml, .github/workflows/pull-request.yml, .github/workflows/static.yml, .markdownlint.yaml, .yamllint.yml, compose.yml
Use [yamllint](https://github.com/adrienverge/yamllint) to to check yaml configuration files. This isn't a very important check IMO since most website changes will not be editing yaml files, and the `_category_.yml` files are pretty simple. However [yamllint is already in the GitHub actions Ubuntu runner](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) so it's low effort to add this check.
I set the yaml linting rules based on what I usually follow but I don't have strong opinions on them as long as they are consistent.
HDDS-10351
- Failing CI run with yamllint added but existing errors not enforced: https://github.com/errose28/ozone-site/actions/runs/8427283082/job/23077474962
- CI on this PR should pass with the fixed yaml files.
=> HDDS-10351. Add GitHub Actions check for yaml formatting.

.github/workflows/static.yml, compose.yml
skywalking-eyes has released [version 0.6.0](https://github.com/apache/skywalking-eyes/releases/tag/v0.6.0). This fixes the warning about deprecated node version from github actions, so we should upgrade to the new version.
HDDS-10698
- [Failing run](https://github.com/errose28/ozone-site/actions/runs/8697967689/job/23854181129) using the new version where a license header was intentionally removed.
- CI on this PR should pass without a warning about using a deprecated node version.
=> HDDS-10698. Bump skywalking-eyes to v0.6.0

package.json, pnpm-lock.yaml
Docusaurus 3.3.2 is out. By upgrading to the 3.3.x line we can use the new [createSitemapItems hook](https://docusaurus.io/blog/releases/3.3#createsitemapitems) to remove the sitemap GitHub Actions job and make that part of the docusaurus build instead (in a follow up change).
HDDS-10902
- Manual preview of website locally seems to work fine.
- Existing CI passes
=> HDDS-10902. Upgrade Docusaurus to 3.3.2

.github/scripts/curl.sh, CONTRIBUTING.md, compose.yml, docusaurus.config.js, package.json
Port 3000 is the default for the Docusaurus dev server which comes from Node/React/Webpack, but it is also the default for Grafana. Ozone devs may have a Grafana instance running in docker already for testing which might conflict with the local preview, especially if they are updating Grafana related documentation. This PR changes the docusaurus default port to 3001 to avoid conflict.
HDDS-11344
- `pnpm start` runs on port 3001 by default
- `docker compose up` runs on port 3001 by default
- `pnpm build && pnpm serve` runs on port 3001 by default
- [CI curl test](https://github.com/errose28/ozone-site/actions/runs/10475183813/job/29011367415) uses the new port and passes.
=> HDDS-11344. Change dev server port to avoid conflict with Grafana.

content/downloads.md, content/release/1.0.0.md, content/release/1.1.0.md, content/release/1.2.1.md, content/release/1.3.0.md, layouts/custompage/downloads.html
Update Downloads page to list only supported releases (currently 1.4.0).  Older releases should not be promoted, but they are available from archives.
Also update other parts of the Downloads page, hopefully an improvement.
https://issues.apache.org/jira/browse/HDDS-11673
```
hugo serve &
open http://localhost:1313/downloads/
```
:eyes:
Screenshot for convenience:
=> HDDS-11673. List supported releases in Downloads page

.gitignore
Untracked items appear when switching between development branches of the website (`master` and `HDDS-9225-website-v2`).
```
$ git status
On branch HDDS-9225-website-v2
Your branch is up to date with 'origin/HDDS-9225-website-v2'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
.hugo_build.lock
```
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
.docusaurus/
```
We should share the same gitignore file between these two.
If this is approved, I'll add the same file to `master`.
https://issues.apache.org/jira/browse/HDDS-11710
```
$ git status
On branch HDDS-11710
nothing to commit, working tree clean
```
With branch created from `master`:
```
$ …
```
=> HDDS-11710. Share gitignore between dev branches

docs/08-developer-guide/04-project/02-release-guide.md
After the vote, we should publish artifacts by moving them within Subversion.
The goal of the voting process is to validate the artifacts being released.  The release manager should not add anything to Subversion after that.  We should move the exact same artifacts checked by the community.
This also simplifies life for the release manager in the non-PMC member case.
https://issues.apache.org/jira/browse/HDDS-11709
```
docker compose up
open "http://localhost:3001/docs/developer-guide/project/release-guide"
```
=> HDDS-11709. Simplify post-vote svn instructions

.markdownlint.yaml
Markdownlint has a [check](https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md024.md) for duplicate headings, but by default it is global. We only want to enforce this for sibling headings, for example the following it ok:
```markdown
```
HDDS-11968
Markdownlint check passed in [this run](https://github.com/errose28/ozone-site/actions/runs/12420912372/job/34679457299), which had duplicate non-sibling headings added [here](https://github.com/errose28/ozone-site/commit/ac1b313303af89f36452d3249c7290ba151d4115)
=> HDDS-11968. Only check sibling headings for duplicate titles in markdown lint.

.github/pull_request_template.md, CONTRIBUTING.md
Provide guidelines in the contributing guide that will help migrate content from the old website to the new website.
HDDS-11972
N/A
=> HDDS-11972. Update contributing guide for migrating content from the current website

CONTRIBUTING.md, cspell.yaml, docs/08-developer-guide/04-project/02-release-guide.md
Right now docs frequently have to add inline spelling ignores to code blocks, especially for command line flags like `-Doption`. The [CSpell docs](https://cspell.org/configuration/patterns/) provide an example pattern to match multi-line markdown code blocks and only apply it to markdown files. We can add this and a similar pattern to ignore inline code blocks and remove all current inline cspell directives from the docs, since they were only needed for code blocks.
HDDS-11970
- [This run](https://github.com/errose28/ozone-site/actions/runs/12422398675) shows [notaword](https://github.com/errose28/ozone-site/commit/374b54098f5c09b52be9a29937bf32c4fd32121e) correctly being flagged by cspell.
- [This run](https://github.com/errose28/ozone-site/actions/runs/12422422447) shows "notaword" …
=> HDDS-11970. Ignore markdown code blocks in cspell

.markdownlint.yaml
The current markdownlint configuration has a typo that mixes the settings for headings and unordered lists:
- [heading-increment](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md001---heading-levels-should-only-increment-by-one-level-at-a-time) uses sensible default values, it does not need to be added to the config
- [heading-style](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md003---heading-style) should be specified as `atx` only
- [ul-style](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md004---unordered-list-style) should be `dash`. This config was incorrectly put under `heading-increment`
This was noticed during the review of #116, where `*` for lists was not flagged.
HDDS-1197.
Check off which of the following tests were …
=> HDDS-11979. Fix heading and list checks in markdownlint.

.markdownlint.yaml, docs/02-quick-start/01-installation/01-docker.md
Added the `Try Ozone With Docker` page
https://issues.apache.org/jira/browse/HDDS-12024
CI: 
~~https://github.com/ptlrs/ozone-site/actions/runs/12626666555~~
~~https://github.com/ptlrs/ozone-site/actions/runs/12704942848~~
~~https://github.com/ptlrs/ozone-site/actions/runs/12705054490~~
~~https://github.com/ptlrs/ozone-site/actions/runs/12705131750~~
~~https://github.com/ptlrs/ozone-site/actions/runs/12715414836~~
https://github.com/ptlrs/ozone-site/actions/runs/12715995405
Tested locally by running the site
=> HDDS-12024. Update try ozone with docker page

docusaurus.config.js
Do not allow search engines to index the under-construction website.
We do this by updating the HTML headers to `<meta name="robots" content="noindex, nofollow">`
via https://docusaurus.io/docs/api/docusaurus-config#noIndex
https://issues.apache.org/jira/browse/HDDS-12128
Check off which of the following tests were done on this change. If additional testing was done, please elaborate here as well.
=> HDDS-12128. Disable indexing of the under-construction site

cspell.yaml
In the [RocksDB docs](https://github.com/facebook/rocksdb/wiki/column-families) "column family" is not hyphenated. Add this check to the website's spell checker.
HDDS-12597
Check off which of the following tests were done on this change. If additional testing was done, please elaborate here as well.
Here is a manual test that "column-family" is flagged but "column family" is not.
=> HDDS-12597. Enforce "column family" without hyphen in spell check

docs/08-developer-guide/04-project/02-release-guide.md
`mvn deploy` rebuilds the project, as it executes all [phases of the default lifecycle](https://maven.apache.org/ref/3.9.9/maven-core/lifecycles.html#default-lifecycle) up to `deploy`.  Not only is it unnecessary, it causes jars to be [different between Maven repo and binary tarball](https://github.com/apache/ozone/discussions/7560).
`mvn deploy:deploy` just executes Maven Deploy Plugin's [`deploy` task](https://maven.apache.org/plugins/maven-deploy-plugin/usage.html#the-deploy-deploy-mojo), which is to upload artifacts to the remote repository.
Flags `-Psign -DskipTests -Dbuildhelper.skipAttach` can be removed, since they are specific to other plugins, which would (before this change) be executed in various lifecycle phases.
Skipping `:ozone-dist` seems to be unnecessary, too.  I don't …
=> HDDS-11925. Fix deploy step in Release Manager guide

docs/08-developer-guide/01-build/03-docker-images.md
Document Ozone Docker images from developer point-of-view.
https://issues.apache.org/jira/browse/HDDS-11916
https://github.com/adoroszlai/ozone-site/actions/runs/13574540904
=> HDDS-11916. Building Ozone Docker Images

docs/08-developer-guide/04-project/02-release-guide.md
- Sample release email should use the `release` KEYS file, not `dev`.
- PMC member should move KEYS from `dev` to `release`, not copy, to avoid confusing leftover `dev` KEYS file.
https://issues.apache.org/jira/browse/HDDS-12675
https://github.com/adoroszlai/ozone-site/actions/runs/14017899383
=> HDDS-12675. Link to release KEYS file in RM guide

docs/08-developer-guide/04-project/02-release-guide.md
Extract "If an issue is found with the artifacts" to a subsection and add cleanup instructions:
- remove previous RC artifacts from Subversion
- discard staging repository from Nexus
https://issues.apache.org/jira/browse/HDDS-12674
https://github.com/adoroszlai/ozone-site/actions/runs/14017840627
=> HDDS-12674. Add cleanup for abandoned RC in RM guide

docs/08-developer-guide/04-project/02-release-guide.md
Update pre-vote Subversion instructions to commit the RC in one step.  In the current version, `svn mkdir https://...` creates the directory in Subversion as a separate commit.
https://issues.apache.org/jira/browse/HDDS-12673
https://github.com/adoroszlai/ozone-site/actions/runs/14017470410
=> HDDS-12673. Streamline pre-vote Subversion instructions

docs/08-developer-guide/04-project/02-release-guide.md
The Release Manager Guide mentions BSD vs. GNU tar, but it's easy to miss.  Add more details.
https://issues.apache.org/jira/browse/HDDS-12672
https://github.com/adoroszlai/ozone-site/actions/runs/14017556094
=> HDDS-12672. Clarify BSD/GNU tar in release manager guide
